[versions]
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
kotlinx-io = "0.8.2"
ndkore = "1.6.7"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
ndkore = { module = "dev.nikdekur:ndkore", version.ref = "ndkore" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }